Classe testing per carrello
develhope/Java27-progetto2-team1 pull request #46
Opened 2024-09-09 15:02 UTC by luigimonteforte5

2024-09-09 15:04 UTC, FedericaSilver reviewed
Mi sembra ci siano tutti i test che ci aveva richiesto Nicola.

2024-09-09 15:22 UTC, FedericaSilver commented on Test/Management/CarrelloTest.java
> +	Utente usr1 = new Cliente();
Qui non è necessario inizializzare il Cliente visto che verrà fatto  nel metodo setUp

2024-09-10 08:21 UTC, aegroto requested changes
I test sono buoni, forse in una prossima PR valuterei se inserire alcuni casi limite in cui si eseguono operazioni non valide e la classe lancia eccezioni (situazione ipotetica perchè il progetto lo presenterete a breve).

2024-09-10 08:21 UTC, aegroto commented on Test/Management/CarrelloTest.java
> +	private Carrello carrello;
La visibilità delle variabili andrebbe assegnata anche nei test per coerenza

2024-09-10 08:21 UTC, aegroto commented on Test/Management/CarrelloTest.java
> +	public void testArrayEquals() {
questo test non verifica il metodo arrayEquals, ma il fatto che il contenuto del carrello corrisponda ai prodotti che sono stati inseriti.

2024-09-10 10:00 UTC, luigimonteforte5 commented on Test/Management/CarrelloTest.java
> +	private Carrello carrello;
Fatto, messo il modificatore private anche alle altre dichiarazioni

2024-09-10 10:00 UTC, luigimonteforte5 commented on Test/Management/CarrelloTest.java
> +	public void testArrayEquals() {
Rinominato il test

2024-09-11 08:25 UTC, aegroto approved these changes

2024-09-11 09:49 UTC, merged